pipeline {
    agent {
        label 'agent193'
    }

    environment {
        DOCKER_REGISTRY = 'docker.io'
        DOCKER_IMAGE = "xyztechnologies"
        DOCKER_HUB = "demsdocker"
        APP_PORT = "8080"           // порт Tomcat у контейнері
        HOST_PORT = "8081"          // порт, на якому expose контейнер (налаштовано у Ansible)
        TOMCAT_APP_PATH = "XYZtechnologies-1.0" // назва .war без розширення
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            tools {
                maven 'maven'
            }
            steps {
                sh 'mvn clean install -Dmaven.test.skip=true'
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ."
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
                    sh "docker tag ${DOCKER_IMAGE} ${DOCKER_HUB}/${DOCKER_IMAGE}"
                    sh "docker push ${DOCKER_HUB}/${DOCKER_IMAGE}"
                }
                echo "Successfully built and uploaded to DockerHub"
            }
        }

        stage('Run Docker container locally') {
            steps {
                sh 'ansible-playbook XYZ_Task3/ansible/ansibleDocCont.yml --connection=local'
                echo "Successfully pulled from DockerHub and started container locally"
            }
        }

        stage('Post-deploy: Check App Deployment in Tomcat') {
            steps {
                script {
                    echo "Waiting for Tomcat to start..."
                    sleep 10

                    echo "Checking deployed app in Tomcat..."
                    sh '''
                        status_code=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:${HOST_PORT}/${TOMCAT_APP_PATH}/)
                        if [ "$status_code" != "200" ]; then
                            echo "❌ Application not available at http://localhost:${HOST_PORT}/${TOMCAT_APP_PATH}/"
                            exit 1
                        else
                            echo "✅ Application successfully deployed to Tomcat at http://localhost:${HOST_PORT}/${TOMCAT_APP_PATH}/"
                        fi
                    '''
                }
            }
        }

       
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh 'ansible-playbook ansible/ansibleK8s.yml --connection=local'
                    echo "Successfully deployed application to Kubernetes cluster"
                }
            }
        }
    }
}
