---
- hosts: localhost
  become: yes
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: demsdocker/xyz-app
        build:
          path: .
        source: build
        state: present

    - name: Run Docker container
      community.docker.docker_container:
        name: xyz-app-container
        image: demsdocker/xyz-app
        state: started
        ports:
          - "1234:8080"
