---
- hosts: localhost
  become: yes
  vars:
    docker_username: "demsdocker" 
    app_name: "xyztechnologies"
  tasks:
    - name: Pull latest image from Docker Hub
      community.docker.docker_image:
        name: "{{ docker_username }}/{{ app_name }}:latest"
        source: pull
        state: present

    - name: Stop and remove any existing container
      community.docker.docker_container:
        name: "{{ app_name }}-container"
        state: absent

    - name: Run Docker container from the pulled image
      community.docker.docker_container:
        name: "{{ app_name }}-container"
        image: "{{ docker_username }}/{{ app_name }}:latest"
        state: started
        ports:
          - "8081:8080" 
