apiVersion: v1
kind: Service
metadata:
  name: xyztechnologies-service
  namespace: xyz-tech
spec:
  type: LoadBalancer  # Change from NodePort to LoadBalancer
  selector:
    app: xyztechnologies  
  ports:
    - port: 80
      targetPort: 8080  
      protocol: TCP