apiVersion: v1
kind: Service
metadata:
  name: xyztechnologies-service
  namespace: xyz-tech
spec:
  selector:
    app: xyztechnologies
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
